### ISSUE TITLE
Hide/Show TabBar

### ISSUE THREAD

**Issue by onisiforos7** [onl1ner/TabBar#1]
hey, great work really. Is it possible to hide the navbar? (remove from screen)|
The idea is when a user clicks on a navigation button and go to another view the navbar should fall down and when the user click on Back button it should appear again.

**Comment by rocketRobin** [comment]
Same issue too

**Comment by onl1ner** [comment]
Hello there! Cool idea, I will implement it as soon as I will have free time. If you also wanna try to do it, go ahead and open your PR 👍

**Comment by bgeisb** [comment]
I just created a pull request on this topic. Feel free to look over it. :)

**Comment by rursache** [comment]
@onl1ner / @bgeisb 
show can i hide the tabbar from a pushed child view?
my hierarchy: 
```
TabBar { 
MainView -> DetailView
SettingsView
} 
```
i want the tabbar to be hidden only in DetailView
thank you!

**Comment by onl1ner** [comment]
Hello, @rursache!

You can pass your state variable that is responsible for the tab bar visiblity to your `DetailView` and manage `TabBar`'s visibility from there :)

**Comment by rursache** [comment]
@onl1ner thanks for the response, i'm still trying to wrap my head around swiftui after years of uikit 😞

**Comment by st-small** [comment]
@onl1ner Thank you very much! Is it possible to animate hiding/showing tab bar? When pushing DetailView tab bar should be move to bottom animately and when user pops back it will animately shows from bottom to top?

**Comment by onl1ner** [comment]
Hello, @st-small!

Yeah, it should animate automatically, but if not you can explicitly run animation by using `withAnimation(_:_:)` function.

Hope it helps :)

**Comment by st-small** [comment]
Now it disappears and appears like `hidden` item. But I ask you about moving tab bar vertically: if disappear, move it bottom, if appear, move up.

[example](https://drive.google.com/file/d/1-0E1ZIalh3w3j4YqFIyxL_wnb9GILrcj/view?usp=sharing)

**Comment by onl1ner** [comment]
Can you share your code please?

**Comment by st-small** [comment]
> Can you share your code please?

Yes, sure https://github.com/st-small/TabBarSUIExample
