### ISSUE TITLE
How to hide tabor dynamically

### ISSUE THREAD

**Issue by st-small** [onl1ner/TabBar#12]
Is it possible to hide tab bar when user selects second tab item only, for example? I want to have several items and if selects first item tabbar should be show but for another (or navigation links) - not.

**Comment by onl1ner** [comment]
Hello, @st-small!

Yeah, it should be possible to achieve by passing binding variable to the `visibility` parameter of the `TabBar` and then just change it to `invisible` when you need to hide a `TabBar`.

So, a sample code of declaring and passing a variable would be like this:

```swift
// <...>

@State private var visibility: TabBarVisibility = .visible

var body: some View {
    TabBar(visibility: $visibility) {
        // <...>
    }
}

// <...>
```

**Comment by onl1ner** [comment]
Closing the issue, if you still have some questions according to this issue please reopen it :)
