### ISSUE TITLE
No releases

### ISSUE THREAD

**Issue by dkk** [onl1ner/TabBar#23]
It would be great if the project had releases and used semantic versioning. It would make the usage and update much easier.

Right now it has to be integrated using branches or commits.

**Comment by onl1ner** [comment]
Hm, it's really strange that you could only integrate library by using branches or commits, because it already uses semantic versioning. You can see all available versions [here](https://github.com/onl1ner/TabBar/tags).

**Comment by dkk** [comment]
sorry, my bad, I forgot that I'm still using my fork, since the PR has not been merged yet.
