### ISSUE TITLE
New Feature? How to change tab from a push/presented view

### ISSUE THREAD

**Issue by gorbat-o** [onl1ner/TabBar#32]
How would you select a tab from a view push/presented ?

Here's an example of how i would love to use this library. 

```
.environment(tabSelection)
```

and in the subview
```
@Environment(TabSelection.self) private var tabSelection
```

**Comment by onl1ner** [comment]
Yes, this is a great idea and would be a valuable improvement! I was actually considering adding it in version 2 of the library. Unfortunately, I’m not able to dedicate as much time as I’d like to developing new features right now. However, if you're up for it, feel free to contribute by adding it to the [2.0.0 branch](https://github.com/onl1ner/TabBar/tree/release/2.0.0).

**Comment by gorbat-o** [comment]
I realized you had a `EnvironmentObject` setup already. It makes this unnecessary unless it becomes deprecated in the future.
