### ISSUE TITLE
couldn't find it in SPM

### ISSUE THREAD

**Issue by Olivia295** [onl1ner/TabBar#6]
copy the url and found 0 results
please help

**Comment by onl1ner** [comment]
Hello,

Try to use this link: https://github.com/onl1ner/TabBar

**Comment by Olivia295** [comment]
i find it and install it correctly
but Example's preview failed and warn Cannot find 'CustomTabBarStyle' in scope
please help and thank u

**Comment by onl1ner** [comment]
`CustomTabBarStyle` and `CustomTabItemStyle` is just a dummy examples of how you can use custom implementation of `TabBarStyle` and `TabItemStyle` protocols respectively.

So, to get `TabBar` work you can just remove `tabBar(style:)` and `tabItem(style:)` setters, and `TabBar` will automatically use default style

**Comment by Olivia295** [comment]
i did it bro and thank u!
